#!/bin/bash

echo "************** RUN ALL ***************"
echo ""

# get parameters
if ([ $# -lt 5 ]) || ([ $# -eq 1 ] && [ "$1" == "-h" -o "$1" == "--help" ]); then
  echo "run-all-with-config <reg username> <reg password> <k8s-context> <profile> <root directory>"
  echo " reg username: container image registry username "
  echo " reg password: container image registry password "
  echo " k8s-context: 사용할 k8s context명. kubectl config view로 context 목록 확인. '.'은 현재 컨텍스트 의미함 "
  echo " profile: 배포대상 환경 프로파일(ex:dev, prod)"  
  echo " root directory: project의 최상위 디렉토리. '.'은 현재 디렉토리 의미함. "
  echo " ex) ./run-all-with-config user1 password1 kubernetes-admin@kubernetes prod ~/work"
  echo " ex) ./run-all-with-config user1 password1 . prod ."
  exit 1
fi

username=$1
password=$2
context=$3
profile=$4
basedir=$5

# download shell if it's not exists
cmdpath=${basedir}/cicd/cmd
which ${cmdpath}/dn-utils 2> /dev/null
if [ $? -eq 1 ]; then
	mkdir -p ${cmdpath} 2> /dev/null
	wget -O ${cmdpath}/dn-utils https://happycloudpak.github.io/cicd-template/cmd/dn-utils
	if [ $? -eq 1 ]; then
		echo "CAN'T download ${cmdpath}/dn-utils"
		exit 1
	fi
fi

# download other shells and templates
${cmdpath}/dn-utils cmd/build-image-with-config,cmd/clear-all-with-config,cmd/deploy-with-config,cmd/read-config,cmd/set-env ${cmdpath}
${cmdpath}/dn-utils dockerfile/Dockerfile ${basepath}/cicd
${cmdpath}/dn-utils deploy/deploy-with-config.yaml ${basepath}/cicd

# build artifactory
${basedir}/mvnw clean package
if [ $? -eq 1 ]; then exit 1; fi

# read only cicd related configuration
${basedir}/cicd/cmd/read-config ${profile} ${basedir} cicd
if [ $? -eq 1 ]; then exit 1; fi

# build & push
${basedir}/cicd/cmd/build-image-with-config ${username} ${password} ${basedir}
if [ $? -eq 1 ]; then exit 1; fi

# deploy
${basedir}/cicd/cmd/deploy-with-config ${context} ${profile} ${basedir} 
if [ $? -eq 1 ]; then exit 1; fi

echo ""
echo "************** END ALL ***************"
exit 0